Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false
